/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as BeliefsRouteImport } from './routes/beliefs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as SecretariatsSlugRouteImport } from './routes/secretariats.$slug'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as DashboardNewsRouteImport } from './routes/dashboard_.news'
import { Route as DashboardNewsNewRouteImport } from './routes/dashboard_.news.new'
import { Route as DashboardNewsIdEditRouteImport } from './routes/dashboard_.news.$id.edit'

const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const BeliefsRoute = BeliefsRouteImport.update({
  id: '/beliefs',
  path: '/beliefs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariatsSlugRoute = SecretariatsSlugRouteImport.update({
  id: '/secretariats/$slug',
  path: '/secretariats/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/dashboard_/news',
  path: '/dashboard/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewsNewRoute = DashboardNewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardNewsRoute,
} as any)
const DashboardNewsIdEditRoute = DashboardNewsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DashboardNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beliefs': typeof BeliefsRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/dashboard/news': typeof DashboardNewsRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/secretariats/$slug': typeof SecretariatsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/dashboard/news/new': typeof DashboardNewsNewRoute
  '/dashboard/news/$id/edit': typeof DashboardNewsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beliefs': typeof BeliefsRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/dashboard/news': typeof DashboardNewsRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/secretariats/$slug': typeof SecretariatsSlugRoute
  '/news': typeof NewsIndexRoute
  '/dashboard/news/new': typeof DashboardNewsNewRoute
  '/dashboard/news/$id/edit': typeof DashboardNewsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beliefs': typeof BeliefsRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/dashboard_/news': typeof DashboardNewsRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/secretariats/$slug': typeof SecretariatsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/dashboard_/news/new': typeof DashboardNewsNewRoute
  '/dashboard_/news/$id/edit': typeof DashboardNewsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beliefs'
    | '/charter'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/membership'
    | '/dashboard/news'
    | '/news/$id'
    | '/secretariats/$slug'
    | '/news/'
    | '/dashboard/news/new'
    | '/dashboard/news/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beliefs'
    | '/charter'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/membership'
    | '/dashboard/news'
    | '/news/$id'
    | '/secretariats/$slug'
    | '/news'
    | '/dashboard/news/new'
    | '/dashboard/news/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/beliefs'
    | '/charter'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/membership'
    | '/dashboard_/news'
    | '/news/$id'
    | '/secretariats/$slug'
    | '/news/'
    | '/dashboard_/news/new'
    | '/dashboard_/news/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeliefsRoute: typeof BeliefsRoute
  CharterRoute: typeof CharterRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  DashboardNewsRoute: typeof DashboardNewsRouteWithChildren
  NewsIdRoute: typeof NewsIdRoute
  SecretariatsSlugRoute: typeof SecretariatsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beliefs': {
      id: '/beliefs'
      path: '/beliefs'
      fullPath: '/beliefs'
      preLoaderRoute: typeof BeliefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretariats/$slug': {
      id: '/secretariats/$slug'
      path: '/secretariats/$slug'
      fullPath: '/secretariats/$slug'
      preLoaderRoute: typeof SecretariatsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/news': {
      id: '/dashboard_/news'
      path: '/dashboard/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/news/new': {
      id: '/dashboard_/news/new'
      path: '/new'
      fullPath: '/dashboard/news/new'
      preLoaderRoute: typeof DashboardNewsNewRouteImport
      parentRoute: typeof DashboardNewsRoute
    }
    '/dashboard_/news/$id/edit': {
      id: '/dashboard_/news/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/news/$id/edit'
      preLoaderRoute: typeof DashboardNewsIdEditRouteImport
      parentRoute: typeof DashboardNewsRoute
    }
  }
}

interface DashboardNewsRouteChildren {
  DashboardNewsNewRoute: typeof DashboardNewsNewRoute
  DashboardNewsIdEditRoute: typeof DashboardNewsIdEditRoute
}

const DashboardNewsRouteChildren: DashboardNewsRouteChildren = {
  DashboardNewsNewRoute: DashboardNewsNewRoute,
  DashboardNewsIdEditRoute: DashboardNewsIdEditRoute,
}

const DashboardNewsRouteWithChildren = DashboardNewsRoute._addFileChildren(
  DashboardNewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeliefsRoute: BeliefsRoute,
  CharterRoute: CharterRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  DashboardNewsRoute: DashboardNewsRouteWithChildren,
  NewsIdRoute: NewsIdRoute,
  SecretariatsSlugRoute: SecretariatsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
